default: &default
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

development:
  <<: *default
  channel_prefix: chat_app_development

test:
  <<: *default
  channel_prefix: chat_app_test

production:
  <<: *default
  channel_prefix: chat_app_production
