
default: &default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default

test:
  primary: &primary_test
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default

production:
  primary:
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default
